Верстка
TatianaKovpak/react-stellar-burger pull request #1
Opened 2023-05-19 20:18 UTC by TatianaKovpak

2023-05-19 21:13 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с `propTypes`
- Хорошая декомпозиция компонентов
- Проект соответствует макету

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте

Проверьте, что в системе контроля версий правильный регистр и при необходимости измените https://noteskeeper.ru/heritage/672/

 <img width="936" alt="Снимок экрана 2023-05-20 в 00 10 44" src="https://github.com/TatianaKovpak/react-stellar-burger/assets/60173362/7f5f6424-fb7c-4bb7-bdfa-4f258f1cb10d">




Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-19 21:13 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const bun = props.filter( i => i.type === 'bun');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-05-19 21:13 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    props: PropTypes.arrayOf(ingredientPropType).isRequired
**Можно лучше**
Лучше пропсы называть по смыслу - т.е. `ingredients`  например

2023-05-19 22:39 UTC, TatianaKovpak reviewed
Исправление регистра

2023-05-20 15:59 UTC, andryxxa93 commented
Супер! Теперь всё работает, промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы!

2023-05-23 05:31 UTC, merged